name: Radiance Bug Report
description: Report rendering issues or crashes related to Radiance.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for reporting!
        To help us debug issues, please provide your hardware environment and Vulkan context.
  - type: dropdown
    id: os_version
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Linux (Ubuntu/Arch/etc.)
        - Windows 10
        - Other
    validations:
      required: true
  - type: input
    id: gpu_model
    attributes:
      label: GPU Model
      placeholder: e.g., NVIDIA RTX 4090, AMD Radeon RX 9070 XT
    validations:
      required: true
  - type: dropdown
    id: gpu_vendor
    attributes:
      label: GPU Vendor
      options:
        - NVIDIA
        - AMD
        - Intel
        - Other
    validations:
      required: true
  - type: input
    id: driver_ver
    attributes:
      label: Driver Version
      placeholder: e.g., 580.126.09 / Adrenalin 26.1.1
    validations:
      required: true
  - type: input
    id: vulkan_sdk
    attributes:
      label: Vulkan SDK Version
      placeholder: e.g., 1.4.313
    validations:
      required: false
  - type: checkboxes
    id: extensions
    attributes:
      label: Vulkan Extensions (Optional)
      description: Check the extensions you are using or suspect are related to the issue.
      options:
        - label: VK_KHR_ray_tracing_pipelin
        - label: VK_KHR_acceleration_structure
        - label: VK_KHR_maintenance5
        - lable: VK_KHR_push_descriptor
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: What happened? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs & Crash Dump
      description: Please paste the Vulkan validation layers output or crash logs here.
      render: shell
    validations:
      required: false
